### PR TITLE
Add support for FTP-Proxy

### PR DESCRIPTION
**Pull request by muffl0n**
As a followup to #75 and #82 I'd like to contribute the code I added locally for using our FTP-Proxy.
I added tests as good as it was possible. Would love to write an integration test someday, but I didn't succeed yet.

### CODE REVIEW

**Comment by willmcgugan** [comment]
Thanks. I'm wondering if it would be more elegant to add a `proxy` argument to the FTPFS constructor?

**Comment by muffl0n** [comment]
Sounds reasonable. I gave it a try in muffl0n/pyfilesystem2@8166826ad8def741d7fa9ecb8435506e8d6a8ca3.

**Comment by willmcgugan** [comment]
Happy with https://github.com/PyFilesystem/pyfilesystem2/pull/136 ? Much the same as your last PR.

**Comment by muffl0n** [comment]
Looks good for me though I can only test it next week when I'm back at the office.
But you can close this PR if you want. I can give more feedback in #136.

**Pull request closed without merging**
