### PR TITLE
WebDAV File System

### PR DESCRIPTION
**Pull request by SerSamgy**
Add WebDAV file system support

### CODE REVIEW

**Comment by willmcgugan** [comment]
Thanks for the contribution. This looks awesome, but I have a concern. I'm trying to keep the dependancies to a minimum, and it looks like webdavclient requires lxml, which is a pain to install on a lot of systems. lxml won't install on Raspberry Pi without some effort, for example.

I think it may be best to keep it as a separate module. I think there are two options; A) manage releases yourself and keep it under your repos or B) move it to the pyfilesystem organization and release it as a namespace package, so you can do `pip install fs.webdav`.

I have no particular preference. If A) I would link to it prominently in the docs and the readme.

What do you think?

**Comment by willmcgugan** [comment]
:+1:

**Comment by zopyx** [comment]
This PR can be closed. It will be replaced soon with a new implementation that will be based on the requests module instead of the pycurl dependency.

**Comment by willmcgugan** [comment]
Ok. Let me know if you need any help with that.

**Pull request closed without merging**
