### PR TITLE
document exceptional cases where the norm does not apply. #398

### PR DESCRIPTION
**Pull request by chfw**
## Type of changes

- [ ] Bug fix
- [ ] New feature
- [x] Documentation / docstrings
- [ ] Tests
- [ ] Other

## Checklist

- [ ] I've run the latest [black](https://github.com/ambv/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [ ] I've added tests for new code.
- [x] I accept that @willmcgugan may be pedantic in the code review.

## Description

Please describe your changes here. If this fixes a bug, please link to the issue, if possible.

related to #398

### CODE REVIEW

**Comment by lurch** [comment]
Presumably this "issue" affects multiple methods, and not _only_ `splitext` ?

**Comment by chfw** [comment]
I would call scope creep, : P

Here is what I can find:

```
$ grep -R 'splitex' fs/
fs//path.py:    "splitext",
fs//path.py:def splitext(path):
fs//path.py:        >>> splitext('baz.txt')
fs//path.py:        >>> splitext('foo/bar/baz.txt')
fs//path.py:        >>> splitext('foo/bar/.foo')
```

**Comment by willmcgugan** [comment]
@chfw The example of an `s3:` path is not a good one, because it implies you would call it with a URL. 

My gut feeling is that most of the confusion could be resolved by strategically adding the word "normalized" to the docstrings. Something like "A tuple containing the **normalized** path and the extension."

Putting a disclaimer on `splitext` probably isn't the way to go because I'm pretty sure all the methods in "fs.path" will return normalized paths, as @lurch pointed out.

**Comment by lurch** [comment]
> I'm pretty sure all the methods in "fs.path" will return normalized paths

Not always - a cursory glance finds that `abspath`, `relpath` and `split` don't normalize their paths - should they? (there may be others, I didn't look at the whole file)

**Comment by althonos** [comment]
Closing, since the proposing change shows a FS URL, which is *not* what the `fs.path` module is designed to work with. To discuss path normalisation for `fs.path` functions, feel free to open another issue!

**Pull request closed without merging**
