### PR TITLE
Fix issue #160 (TarFS implicit directory bug)

### LINKED ISSUE #160: PyFilesystem can't find existing file in tar-fs
I wrote a stackoverflow post about this, I'm not entirely sure, but I suspect this to be a bug:

https://stackoverflow.com/questions/49811622/pyfilesystem-cant-find-existing-file-in-tar-fs

### PR DESCRIPTION
**Pull request by althonos**
Hi Will, 

just a quick PR to fix #160, with regression tests. Is there any `unique` iterator filter in the `fs` codebase ? It could avoid using a set just to filter out duplicates in the `listdir` patch.

### CODE REVIEW

**Comment by willmcgugan** [comment]
Great, thanks. Will do a release once that's in.

multifs filters out duplicate paths, and I did some research. It seems that this is the fastest way to filter duplicates while preserving order:

```
directory = list(OrderedDict.fromkeys(directory))
```

**Comment by althonos** [comment]
> multifs filters out duplicate paths, and I did some research. It seems that this is the fastest way to filter duplicates while preserving order: `directory = list(OrderedDict.fromkeys(directory))`

I use the `unique_everseen` recipe most of the time, but this is a nice trick ! I'll add it right now.

**Comment by althonos** [comment]
Yes, no more work intended !

 I'll rebase the typing branch as well.

**Comment by willmcgugan** [comment]
Great, thanks!

**Pull request merged**
