### PR TITLE
Drop usage of `pkg_resources`

### PR DESCRIPTION
**Pull request by edgarrmondragon**
## Type of changes

- Bug fix

## Checklist

- [ ] I've run the latest [black](https://github.com/ambv/black) with default args on new code.
- [ ] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @PyFilesystem/maintainers may be pedantic in the code review.

## Description

Drop `pkg_resources` in favor of the `importlib.metadata` API.

Closes https://github.com/PyFilesystem/pyfilesystem2/issues/356

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
@althonos the tests that fail seem to do so (rather randomly?) due to a `DeprecationWarning` in the Python 3.10 `importlib.metadata` API. There's a few options I can think of:

- Kludgy solution that supports both the deprecated and new APIs
- Require `importlib_metadata==2.0.0` for all Python versions (even the newer ones) and use the _legacy_ API
- Drop support for Python 2.7 (EOL Jan 2021) and Python 3.5 (EOL Sept 2020) and require `importlib_metadata>=3.6.0;<4.9.0` for Python 3.6 and 3.7.

**Comment by edgarrmondragon** [comment]
@matrss tbh the project feels abandoned 😢

**Comment by lurch** [comment]
I occasionally review some of the PRs in this project, but I don't know anything about the code being modified here, so I won't be reviewing this one.

> Drop support for Python 2.7

Yeah, see also https://github.com/PyFilesystem/pyfilesystem2/issues/317

**Comment by anthrotype** [comment]
> tbh the project feels abandoned 😢

oh.. @willmcgugan is it so?

**Comment by anthrotype** [comment]
> [willmcgugan](https://github.com/willmcgugan) is not maintaining this anymore

oh, I somehow missed that, thanks for the clarification/reminder.

> "if it's not broken don't fix it" 

definitely makes sense. Good luck with the PhD!

**Comment by AbdealiLoKo** [comment]
@althonos would you like some help maintaining it ?
I use pyfilesystem actively and am happy to help maintain.
I was looking to fix the warnings from pyfilesystem related to pkg_resources and came across this PR

**Comment by eli-schwartz** [comment]
> @althonos the tests that fail seem to do so (rather randomly?) due to a `DeprecationWarning` in the Python 3.10 `importlib.metadata` API. There's a few options I can think of:

I'm probably missing something since the CI logs are long gone...

Why would this fail at all? A DeprecationWarning should not cause CI failures since the pytest config doesn't appear to be catching it as an error. You just get:
```
2654 passed, 26 skipped, 1703 warnings in 38.20s
```

**Comment by eli-schwartz** [comment]
Either way I think the obviously correct approach is to handle a fallback to the legacy API if needed, since that means you don't have to block this PR on resolving the python2 question.

**Comment by anthrotype** [comment]
hello! what it would take to get this PR to the finish line?

**Comment by edgarrmondragon** [comment]
The flaky 3.10 tests pass locally 🤔

**Comment by eli-schwartz** [comment]
That doesn't look like a flake to me -- it's running on python 3.7, not 3.10. And, as I said above:

> Either way I think the obviously correct approach is to handle a fallback to the legacy API if needed, since that means you don't have to block this PR on resolving the python2 question.

But currently you're exclusively using the legacy API, which is broken.

**Comment by edgarrmondragon** [comment]
I'm closing the PR since I won't be able to finish this any time soon :)

**Comment by mxmlnkn** [comment]
> I've been fine with the "if it's not broken don't fix it" for now.

Unfortunately, with Python 3.12, it is broken now. Installing PyFilesystem2 seems to still work, but trying to import it, I get: 

```
Traceback (most recent call last):
  [...]
  File "squashfs-root/opt/python3.12/lib/python3.12/site-packages/fs/__init__.py", line 4, in <module>
    __import__("pkg_resources").declare_namespace(__name__)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by eli-schwartz** [comment]
Submitted an alternative PR at https://github.com/PyFilesystem/pyfilesystem2/pull/589 / https://github.com/PyFilesystem/pyfilesystem2/pull/590

**Pull request closed without merging**
