### PR TITLE
Remove pytz

### LINKED ISSUE #516: Move away from pytz
pytz is known for doing funky things that aren't really compatible with the rest of the python ecosystem and in some cases simply don't make sense. Their timezone objects aren't even compatible with actual Python tzinfo objects.

Here's a discussion from matplotlib where they decided to drop it in favour of dateutil, which has also been recommended by the python documentation for years now:

https://github.com/matplotlib/matplotlib/issues/10443/

Alternatively (if you're willing to drop support for Python 3.8 and below), Python 3.9 has a new built-in zoneinfo module in the stdlib that provides the common use case of just loading timezone objects by name with accurate timezone info.

### PR DESCRIPTION
**Pull request by djmattyg007**
## Type of changes

- Other

## Checklist

- [x] I've run the latest [black](https://github.com/ambv/black) with default args on new code.
- [x] I've updated CHANGELOG.md and CONTRIBUTORS.md where appropriate.
- [x] I've added tests for new code.
- [x] I accept that @PyFilesystem/maintainers may be pedantic in the code review.

## Description

Everything that pytz was being utilised for can be serviced perfectly
fine by the standard library. Meanwhile, pytz is known as a footgun:

https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html

Fixes #516

### CODE REVIEW

**Comment by lurch** [comment]
Could you fix up the tests please?

**Comment by djmattyg007** [comment]
I've updated the PR with some compatibility code for python2.

**Comment by lurch** [comment]
Looks like you forgot to add the `except ImportError` to the test-code?

**Comment by djmattyg007** [comment]
Sorry about that. I've updated the PR again.

**Comment by lurch** [comment]
Thanks. Unit-tests now all pass, but `lint (typecheck)` is saying`fs/time.py:14: error: Incompatible import of "timezone" (imported name has type Module, local name has type "Type[timezone]")` ?  (I wonder if you need to make `timezone` a class within the `_tzcompat.py` file? :shrug: )

**Comment by djmattyg007** [comment]
I've updated the PR again.

**Comment by djmattyg007** [comment]
I tried running the type-checking locally, and it seemed to produce a similar error.

I also tried upgrading mypy, and that produced a litany of errors totally unrelated to my changes.

I've gotta be honest, I have very little interest in attempting to deal with python2. It's been EOL for more than two years. Support for it should be removed. In lieu of that, I'm just going to add `type: ignore` directives to the relevant code. Python2 is not worth any more time than that to anyone.

**Comment by lurch** [comment]
Thanks. LGTM, but I'll let one of the other maintainers merge it.

**Comment by althonos** [comment]
I'm fine with the `type: ignore` as well, in particular if it happens in Python 2 compat code.

**Comment by althonos** [comment]
(I'll review and merge when I get home)

**Comment by djmattyg007** [comment]
Hi folks, I was wondering if there's anything more I need to do to get this PR merged.

**Comment by althonos** [comment]
@djmattyg007 : sorry, got caught by real-life work. I'll do a round of merging so that I can address several issues at once before the next release.

**Comment by althonos** [comment]
Thanks!

**Pull request merged**
